AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS cluster ecs service role"
Parameters: 
  Project:
    Default: ecs-playground
    Description: Name of the Project
    Type: String
Resources:
  ServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${Project}-service'
      Path: /
      AssumeRolePolicyDocument: 
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${Project}-service'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: ECSTaskManagement
                Effect: Allow
                Action:
                  - 'ec2:AttachNetworkInterface'
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:CreateNetworkInterfacePermission'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DeleteNetworkInterfacePermission'
                  - 'ec2:Describe*'
                  - 'ec2:DetachNetworkInterface'
                  - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
                  - 'elasticloadbalancing:DeregisterTargets'
                  - 'elasticloadbalancing:Describe*'
                  - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
                  - 'elasticloadbalancing:RegisterTargets'
                  - 'route53:ChangeResourceRecordSets'
                  - 'route53:CreateHealthCheck'
                  - 'route53:DeleteHealthCheck'
                  - 'route53:Get*'
                  - 'route53:List*'
                  - 'route53:UpdateHealthCheck'
                  - 'servicediscovery:DeregisterInstance'
                  - 'servicediscovery:Get*'
                  - 'servicediscovery:List*'
                  - 'servicediscovery:RegisterInstance'
                  - 'servicediscovery:UpdateInstanceCustomHealthStatus'
                Resource: '*'
Outputs:
  ServiceRole:
    Description: A reference to the created service role
    Value: !Ref ServiceRole
