AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS template for AWS Cloudformation."
Parameters:
  ClusterName:
    Default: ecs-playground
    Description: Name of the cluster 
    Type: String
  VPC:
    Description: The VPC for this cluster
    Type: 'AWS::EC2::VPC::Id'
  Subnets:
    Description: List of subnets for the ECS Instances
    Type: 'List<AWS::EC2::Subnet::Id>'
  AvailabilityZones:
    Description: List of Availability Zones
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  ECSRoleName:
    Default: ecs-playground
    Description: Name ECS > autoscaling > launchconfiguration > iamprofile role 
    Type: String
  ImageId:
    Default: ami-06f9b7c717914a382
    Description: ECS latest AMI image id 
    Type: String
  SecurityGroup:
    Default: sg-0655b947704f11744
    Description:  Security Group name
    Type: String
  InstanceType:
    Description: The Instance Type
    Type: String
    Default: t3.small
  KeyName:
    Description: The Instance key name
    Type: String
    Default: ecs-playground

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ClusterName}
  ECSLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      AssociatePublicIpAddress: true
      IamInstanceProfile: !Ref IAMInstanceProfile
      ImageId: !Ref ImageId
      SecurityGroups: [!Ref SecurityGroup]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo ECS_CLUSTER=${ClusterName} >> /etc/ecs/ecs.config
  ECSAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AvailabilityZones: !Ref AvailabilityZones
      Cooldown: '30'
      DesiredCapacity: '1'
      MinSize: '1'
      MaxSize: '1'
      HealthCheckGracePeriod: '50'
      HealthCheckType: EC2
      LaunchConfigurationName: !Ref ECSLaunchConfiguration
      MetricsCollection:
        - Granularity: 1Minute
      VPCZoneIdentifier: !Ref Subnets
      Tags:
        - PropagateAtLaunch: 'true'
          Key: Name
          Value: !Join 
            - '-'
            - - !Ref ClusterName
              - Node
        - PropagateAtLaunch: 'true'
          Key: ECS_Cluster
          Value: !Ref ClusterName


  IAMInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref ECSRoleName
      
  
